# Generated by Django 3.2 on 2023-12-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Engine',
                'verbose_name_plural': 'Engines',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10, verbose_name='Number plate')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorizations.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Car bouth by user',
                'verbose_name_plural': 'Cars bouth by users',
                'ordering': ['-id'],
            },
        ),
    ]
