# Generated by Django 3.2 on 2024-02-17 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import motorizations.validators
import utils.django.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Engine',
                'verbose_name_plural': 'Engines',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Name')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorizations.engine', verbose_name='Engine')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z]*$')], verbose_name='Number plate')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user', to='motorizations.car', verbose_name='Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user_created', to=settings.AUTH_USER_MODEL, validators=[motorizations.validators.user_write_authorization_validator, utils.django.validators.user_is_active_validator], verbose_name='User')),
            ],
            options={
                'verbose_name': 'Car bouth by user',
                'verbose_name_plural': 'Cars bouth by users',
                'ordering': ['-id'],
                'unique_together': {('car', 'user', 'number_plate')},
            },
        ),
    ]
