# Generated by Django 3.2 on 2024-06-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import motorizations.managers
import motorizations.validators
import utils.django.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motorizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='caruser',
            managers=[
                ('objects', motorizations.managers.CarUserManager()),
                ('superuser_objects', motorizations.managers.CarUserSuperUserManager()),
                ('exclude_superuser_objects', motorizations.managers.CarUserExcludeSuperUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='caruser',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user_created', to=settings.AUTH_USER_MODEL, validators=[motorizations.validators.user_write_authorization_validator, utils.django.validators.user_is_active_validator], verbose_name='User created'),
        ),
    ]
