# Generated by Django 3.2 on 2024-02-03 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import motorizations.validators
import utils.django.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motorizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_user',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='car_user',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_user_created', to='users.user', validators=[motorizations.validators.user_write_authorization_validator, utils.django.validators.user_is_active_validator], verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car_user',
            name='number_plate',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9a-zA-Z]*$')], verbose_name='Number plate'),
        ),
    ]
