# Generated by Django 3.2 on 2024-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorizations', '0003_auto_20240825_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentations',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='docs',
            field=models.ManyToManyField(related_name='car_docs', to='motorizations.Documentation', verbose_name='Documentation'),
        ),
    ]
